name: Deploy Portfolio

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev

    - name: Build and install git-crypt
      run: |
        curl -L -o git-crypt.tar.gz https://www.agwa.name/projects/git-crypt/downloads/git-crypt-0.7.0.tar.gz
        tar -xzvf git-crypt.tar.gz
        cd git-crypt-0.7.0
        make
        sudo cp git-crypt /usr/local/bin/
    
    - name: Unlock git-crypt
      run: |
        echo "${{ secrets.GIT_CRYPT_KEY }}" | base64 -d > git-crypt-key
        git-crypt unlock git-crypt-key
        rm git-crypt-key
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "build/"
        target: "/var/www/foxous-portfolio"
        strip_components: 1
        
    - name: Set permissions
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          chown -R www-data:www-data /var/www/foxous-portfolio
          chmod -R 755 /var/www/foxous-portfolio
